# Generated by Django 3.0.8 on 2020-07-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
